% encoding: utf-8
% author: Tegredum
% MATLAB version: R2024b
% 一个用于测试 TransUtils 单元的测试程序。
%%
clear
close all
%% 测试 velDir_2_velVec 方法
% case 1：正北方向
V = 5.0;
theta = 0.0;
psi = 0.0;
disp(['正北方向计算结果：',...
    num2str(TransUtils_teg.normDir_2_vec(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)')])
% case 2：垂直向上
V = 10.0;
theta = pi / 2.0;
psi = 0.0;
disp(['垂直向上计算结果：',...
    num2str(TransUtils_teg.normDir_2_vec(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)')])
% case 3：弹道倾角与偏角均为 45 度
V = sqrt(2.0);
theta = pi / 4.0;
psi = pi / 4.0;
disp(['弹道倾角与偏角均为 45 度计算结果：',...
    num2str(TransUtils_teg.normDir_2_vec(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)')])
%% 测试 par_vec_par_norm 方法
% case 1：方向角全为 0
V = 1.0;
V_delta = 1e-3;
theta = 0.0;
psi = 0.0;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V + V_delta,...
    'theta', theta,...
    'psi', psi);
disp(['case 1：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_norm(...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / V_delta)')])
% case 2：弹道倾角 pi / 3，弹道偏角 pi / 6
V = 1.0;
V_delta = 1e-3;
theta = pi / 3.0;
psi = pi / 6.0;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V + V_delta,...
    'theta', theta,...
    'psi', psi);
disp(['case 2：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_norm(...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / V_delta)')])
%% 测试 par_vec_par_theta 方法
% case 1：方向角全为 0
V = 3.0;
theta = 0.0;
theta_delta = 1e-5;
psi = 0.0;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta + theta_delta,...
    'psi', psi);
disp(['case 1：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_theta(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / theta_delta)')])
% case 2：弹道倾角 pi / 4，弹道偏角 pi / 4
V = 2.0;
theta = pi / 4.0;
theta_delta = 1e-5;
psi = pi / 4.0;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta + theta_delta,...
    'psi', psi);
disp(['case 2：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_theta(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / theta_delta)')])
%% 测试 par_vec_par_psi 方法
% case 1：方向角全为 0
V = 5.0;
theta = 0.0;
psi = 0.0;
psi_delta = 1e-5;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi + psi_delta);
disp(['case 1：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_psi(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / psi_delta)')])
% case 2：弹道倾角 pi / 3，弹道偏角 pi / 2
V = 4.0;
theta = pi / 3.0;
psi = pi / 2.0;
psi_delta = 1e-5;
velVec_original = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi);
velVec_with_delta = TransUtils_teg.normDir_2_vec(...
    'norm', V,...
    'theta', theta,...
    'psi', psi + psi_delta);
disp(['case 2：解析解与数值解偏差：',...
    num2str((TransUtils_teg.par_vec_par_psi(...
        'norm', V,...
        'theta', theta,...
        'psi', psi)...
        - (velVec_with_delta - velVec_original) / psi_delta)')])